### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by stefadrian** [kurenai-ryu/pyzk#10]
Hello !
I ran the program and did all configurations, (in some others programs it required me to install al pl*.dll s)  and all worked out i was able to run  this program . But it shows me Timed out... on basic test .
I tried to debug it and found that it takes infinite time when it sends the connect command CMD_CONNECT ( 1000 )

And i dont know what to do anymore :)) .Can somebdy help me, i have to do this project for somebody where i have to get the users and live logs for zk c3-200 . 

And the ip and port are all good, and i tried force udp false/true/undefined
I tried also no password instead of 0 , and 'admin' .
Thank you !

**Comment by kurenai-ryu** [comment]
add verbose mode, and log the communication with Wireshark

**Comment by stefadrian** [comment]
Hello ,thanks for responding so fast , i ran wireshark for the basic_test, is this alright ? i added verbose=True in code :
```
zk = ZK(ip='192.168.0.201', port=4370, timeout=5, password=0,
        force_udp=False, ommit_ping=False, verbose=True)
        
```
and this is wireshark output and basic test output : 

this is the link to the files , couldnt upload them here :
[https://drive.google.com/file/d/1snojJy5DN-GRAX9gCI7FaYVJNcZayy0B/view?usp=sharing](url)

**Comment by kurenai-ryu** [comment]
as the message stated, It can't connect to the device. I see in the pcap file that the communication started correctly, but there isn't a valid response.

so in conclusion: the PyZk library is not compatible with the firmware of your device.

try using a valid software (like zkacces) and capture the communication with wireshark, if the steps to implement are easy maybe it can integrated in the library, but don't get your hopes up, as I maintain this project on my free time.

reopen if necessary
