### ISSUE TITLE
get_user_template can't work

### ISSUE THREAD

**Issue by dongqisilent** [kurenai-ryu/pyzk#4]
**Describe the bug**
the function get_user_template() always can't work
**To Reproduce**
1. use get_user_template() can get fingers
2.use get_user_template(2) can't get finger, t always return None ,I am sure, the uid = 2 has finger

**System (please complete the following information):**
 - OS: os
 - Python version 3.6

**Additional context**
the device is iface702

**Comment by kurenai-ryu** [comment]
well, I think you mean  that `get_templates()` works but when trying to use `get_user_template(2) # which means uid=2` it doesn't get your template...

if so, please note that `get_user_template` has additional parameters, in your case, by default it reads the pinky finger (temp_id=0) if you know the finger index you should try to read with `get_user_template(2,5) #in case you want to read finger 5` or try to populate an array with all fingers

```python
templates = []
for finger in range(10):
  tmp = conn.get_user_template(2, finger)
  if tmp: #it's None if empty
    templates.append(tmp)
```

> lastly remember that uid and user_id are different, (for now, please get the correct uid with the `get_users()` command


if it still doesn't work, please send some example code, with results (and importantly a wireshark capture to compare if the command was issued correctly)

**Comment by dongqisilent** [comment]
thank you,it works
